---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kitchensink-bot
  namespace: kitchensink-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kitchensink-bot
rules:
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - operator.tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kitchensink-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kitchensink-bot
subjects:
- kind: ServiceAccount
  name: kitchensink-bot
  namespace: kitchensink-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kitchensink-bot-self-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
subjects:
- kind: ServiceAccount
  name: kitchensink-bot
  namespace: kitchensink-bot
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kitchensink-bot-db-pvc
  namespace: kitchensink-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kitchensink-bot
  name: kitchensink-bot
  namespace: kitchensink-bot
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: kitchensink-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kitchensink-bot
    app.openshift.io/runtime: python
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: 'main'
    app.openshift.io/vcs-uri: 'https://github.com/atarazana/kitchensink-bot'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"kitchensink-bot:latest","namespace":"kitchensink-bot"},"fieldPath":"spec.template.spec.containers[?(@.name==\"kitchensink-bot\")].image","pause":"false"}]
  name: kitchensink-bot
  namespace: kitchensink-bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kitchensink-bot
  template:
    metadata:
      labels:
        app: kitchensink-bot
    spec:
      serviceAccountName: kitchensink-bot
      volumes:
        - name: kitchensink-bot-db-pvc
          persistentVolumeClaim:
            claimName: kitchensink-bot-db-pvc
        - name: data-secret-volume
          secret:
            secretName: kitchensink-bot-data
      containers:
      - name: kitchensink-bot
        # image: quay.io/atarazana/kitchensink-bot:1.0.0
        image: image-registry.openshift-image-registry.svc:5000/kitchensink-bot/kitchensink-bot:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '500m'
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: kitchensink-bot-db-pvc
          mountPath: /db
        - name: data-secret-volume
          mountPath: /data
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom: 
        - secretRef:
            name: kitchensink-bot-env
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: kitchensink-bot
  name: kitchensink-bot
  namespace: kitchensink-bot
spec:
  to:
    kind: Service
    name: kitchensink-bot
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: 'main'
    app.openshift.io/vcs-uri: 'https://github.com/atarazana/kitchensink-bot'
  name: kitchensink-bot
  labels:
    app: kitchensink-bot
    app.kubernetes.io/component: kitchensink-bot
    app.kubernetes.io/instance: kitchensink-bot
    app.kubernetes.io/name: kitchensink-bot
    app.kubernetes.io/part-of: kitchensink-bot-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: 'main'
    app.openshift.io/vcs-uri: 'https://github.com/atarazana/kitchensink-bot'
  name: kitchensink-bot
  labels:
    app: kitchensink-bot
    app.kubernetes.io/component: kitchensink-bot
    app.kubernetes.io/instance: kitchensink-bot
    app.kubernetes.io/name: kitchensink-bot
    app.kubernetes.io/part-of: kitchensink-bot-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'kitchensink-bot:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/atarazana/kitchensink-bot'
      ref: 'main'
    contextDir: /
  # triggers:
  #   - type: Generic
  #     generic:
  #       secretReference:
  #         name: kitchensink-bot-generic-webhook-secret
  #   - type: GitHub
  #     github:
  #       secretReference:
  #         name: kitchensink-bot-github-webhook-secret
  #   - type: ConfigChange
  runPolicy: Serial

