kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodejs-18
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: {{ quote .Values.nodejsBuilderImage }}
      generation: 1
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
    